name: 'Criterion Pages'
description: 'Use criterion.rs benchmarks within your gh pages'
branding:
    icon: bar-chart-2
    color: black
inputs:
    root:
        description: 'Root directory the benchmarks are run from (. or ./.. path to package)'
        required: true
        default: '.'
    path:
        description: 'Target directory for @actions/pages to build from'
        required: true
        default: './bench'
outputs:
    created_dir:
        description: 'The directory to target'
runs:
    using: 'node20'
    main: 'dist/index.js'
